controller_list:
  - name: ""
    action_ns: yara_controller
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 10.0
    allowed_goal_duration_margin: 10.0
    default: true
    joints:
      - base_to_link_1
      - link_1_to_link_2
      - link_2_to_link_3
      - link_3_to_link_4
      - link_4_to_link_5
      - link_5_to_link_6     