controller_list:
  - name: fake_yara_controller
    joints:
      - base_to_link_1
      - link_1_to_link_2
      - link_2_to_link_3
      - link_3_to_link_4
      - link_4_to_link_5
      - link_5_to_link_6
  - name: fake_hand_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: yara
    pose: neutral