# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: yara_arm
  joint_model_group_pose: neutral
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_link_1
    - link_1_to_link_2
    - link_2_to_link_3
    - link_3_to_link_4
    - link_4_to_link_5
    - link_5_to_palm
    - palm_to_servo_gear
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ""
    action_ns: yara_controller
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 10.0
    allowed_goal_duration_margin: 10.0
    default: true
    joints:
      - base_to_link_1
      - link_1_to_link_2
      - link_2_to_link_3
      - link_3_to_link_4
      - link_4_to_link_5
      - link_5_to_palm    
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_to_link_1
    - link_1_to_link_2
    - link_2_to_link_3
    - link_3_to_link_4
    - link_4_to_link_5
    - link_5_to_palm
  gains:
    base_to_link_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_1_to_link_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_2_to_link_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_3_to_link_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_4_to_link_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_5_to_palm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1